import type { GeneratedFile } from '@design2code/design-ast';
import type { GeneratorContext } from '@design2code/generator-sdk';
import { toPascalCase, toSnakeCase } from './naming.js';

export function generateProjectScaffold(
  context: GeneratorContext,
  createFile: (path: string, content: string, kind: GeneratedFile['kind']) => GeneratedFile,
): GeneratedFile[] {
  const screens = context.document.screens;
  const routeImports = screens
    .map((s) => {
      const snake = toSnakeCase(s.name);
      return `import '../../features/${snake}/presentation/pages/${snake}_page.dart';`;
    })
    .join('\n');

  const routes = screens
    .map((s) => {
      const pascal = toPascalCase(s.name);
      const route = s.route ?? `/${toSnakeCase(s.name).replace(/_/g, '-')}`;
      return `      GoRoute(
        path: '${route}',
        name: '${toSnakeCase(s.name)}',
        builder: (context, state) => const ${pascal}Page(),
      ),`;
    })
    .join('\n');

  const defaultRoute =
    screens.length === 0
      ? `      GoRoute(
        path: '/',
        builder: (context, state) => const Scaffold(
          body: Center(child: Text('Design2Code App')),
        ),
      ),`
      : routes;

  return [
    createFile(
      'lib/main.dart',
      `import 'package:flutter/material.dart';
import 'core/router/app_router.dart';
import 'core/theme/app_theme.dart';

void main() {
  WidgetsFlutterBinding.ensureInitialized();
  runApp(const Design2CodeApp());
}

class Design2CodeApp extends StatelessWidget {
  const Design2CodeApp({super.key});

  @override
  Widget build(BuildContext context) {
    return MaterialApp.router(
      title: 'Design2Code App',
      debugShowCheckedModeBanner: false,
      theme: AppTheme.light,
      darkTheme: AppTheme.dark,
      themeMode: ThemeMode.system,
      routerConfig: AppRouter.router,
    );
  }
}
`,
      'project',
    ),
    createFile(
      'lib/core/router/app_router.dart',
      `import 'package:flutter/material.dart';
import 'package:go_router/go_router.dart';
${routeImports}

/// App routing — GoRouter configuration
abstract final class AppRouter {
  AppRouter._();

  static final GoRouter router = GoRouter(
    initialLocation: '/',
    routes: [
${defaultRoute}
    ],
    errorBuilder: (context, state) => Scaffold(
      body: Center(child: Text('Page not found: \${state.uri}')),
    ),
  );
}
`,
      'route',
    ),
    createFile(
      'analysis_options.yaml',
      `include: package:flutter_lints/flutter.yaml

linter:
  rules:
    prefer_const_constructors: true
    prefer_const_declarations: true
    avoid_print: true
    always_use_package_imports: true
`,
      'config',
    ),
    createFile('pubspec.yaml', generatePubspec(), 'config'),
  ];
}

function generatePubspec(): string {
  return `name: design2code_app
description: Generated by Design2Code AI — Clean Architecture + BLoC
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.5.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_bloc: ^8.1.6
  equatable: ^2.0.7
  go_router: ^14.6.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  bloc_test: ^9.1.7
  mocktail: ^1.0.4
`;
}
