import type { GenerationResult, DesignNode, GeneratedFile } from '@design2code/design-ast';
import { BaseGenerator, type GeneratorContext } from '@design2code/generator-sdk';
import {
  ReactFidelityEmitter,
  generateCompoundFiles,
  reactFamilyCompoundHooks,
  FigmaFidelityEngine,
  type ComponentRegistry,
  type CompoundEmitter,
  type CompoundPlan,
} from '@design2code/generator-sdk';
import { generateCSSVariables } from '@design2code/design-token-engine';

export class NextjsGenerator extends BaseGenerator {
  readonly name = 'nextjs';
  readonly framework = 'nextjs';

  async generate(context: GeneratorContext): Promise<GenerationResult> {
    const files: GeneratedFile[] = [];
    const nodes = this.filterNodesByScope(context);
    const fidelity = new FigmaFidelityEngine();

    const css = generateCSSVariables(context.document.tokens);
    files.push(this.createFile(css.path, css.content, 'css', 'token'));

    files.push(
      this.createFile(
        'src/styles/figma-reset.css',
        `/* Pixel-perfect base reset for Figma-generated UI */
*, *::before, *::after { box-sizing: border-box; }
img { display: block; max-width: 100%; }
button { cursor: pointer; border: none; font: inherit; }
`,
        'css',
        'token',
      ),
    );

    const isFeatureScope = context.options.scope === 'feature';
    const isCompoundScope =
      context.options.scope === 'component' ||
      context.options.scope === 'screen' ||
      isFeatureScope;

    if (isCompoundScope) {
      const hooks = this.createHooks(isFeatureScope);

      for (const node of nodes) {
        const score = fidelity.fidelityScore(node);
        const { files: compoundFiles, plan } = generateCompoundFiles(
          node,
          context,
          (path, content, language, _kind) =>
            this.createFile(
              path,
              content.replace('FIGMA_FIDELITY_SCORE', String(score)),
              language,
              isFeatureScope ? 'feature' : context.options.scope === 'component' ? 'component' : 'screen',
            ),
          hooks,
        );
        files.push(...compoundFiles);

        if (context.options.scope === 'screen') {
          const pageName = this.toPascalCase(node.name);
          const kebab = this.toKebabCase(node.name);
          files.push(
            this.createFile(
              `src/app/${kebab}/page.tsx`,
              this.wrapAsNextPage(pageName, kebab, score),
              'typescript',
              'screen',
            ),
          );
        }

        if (isFeatureScope) {
          files.push(...this.generateFeatureModule(context, plan));
        }
      }
    }

    if (context.options.scope === 'project') {
      files.push(...this.generateProjectScaffold(context));
    }

    const avgFidelity =
      nodes.length > 0
        ? Math.round(nodes.reduce((sum, n) => sum + fidelity.fidelityScore(n), 0) / nodes.length)
        : 0;

    return {
      files,
      warnings:
        avgFidelity < 70
          ? ['Some nodes have incomplete Figma data — enable AI enhancement for better fidelity']
          : [],
      metadata: { framework: 'nextjs', nodeCount: nodes.length, figmaFidelity: avgFidelity },
    };
  }

  private createHooks(isFeatureScope: boolean) {
    return reactFamilyCompoundHooks(
      (node, name, emitter, registry, imports, _isRoot) =>
        this.generateCompoundComponent(node, name, emitter as ReactFidelityEmitter, registry, imports),
      () => new ReactFidelityEmitter() as CompoundEmitter,
      (rootName, ctx) =>
        isFeatureScope
          ? `src/features/${this.toKebabCase(ctx.document.name)}/components/${this.toKebabCase(rootName)}`
          : `src/components/${this.toKebabCase(rootName)}`,
      (plan, ctx) =>
        isFeatureScope
          ? `src/features/${this.toKebabCase(ctx.document.name)}/components/${plan.rootName}.tsx`
          : `src/components/${plan.rootName}.tsx`,
    );
  }

  private generateCompoundComponent(
    node: DesignNode,
    name: string,
    emitter: ReactFidelityEmitter,
    registry: ComponentRegistry,
    imports: string[],
  ): string {
    emitter.setRegistry(registry);
    const body = emitter.renderJSX(node, 3, registry);
    const importBlock = imports.length > 0 ? `${imports.join('\n')}\n\n` : '';

    return `${importBlock}/** Compound component — composes reusable sub-components (Figma fidelity FIGMA_FIDELITY_SCORE%) */
export interface ${name}Props {
  className?: string;
}

export function ${name}({ className }: ${name}Props) {
  return (
    <div className={className}>
${body}
    </div>
  );
}
`;
  }

  private wrapAsNextPage(pageName: string, kebab: string, score: number): string {
    const importPath = `@/components/${kebab}`;
    return `import { ${pageName} } from '${importPath}';
import type { Metadata } from 'next';

export const metadata: Metadata = {
  title: '${pageName.replace(/Page$/, '')}',
  description: 'Generated by Design2Code — Figma fidelity ${score}%',
};

export default function ${pageName}Page() {
  return (
    <main style={{ minHeight: '100vh', display: 'flex', flexDirection: 'column' }}>
      <${pageName} />
    </main>
  );
}
`;
  }

  private generateFeatureModule(context: GeneratorContext, plan: CompoundPlan): GeneratedFile[] {
    const name = this.toPascalCase(context.document.name);
    const kebab = this.toKebabCase(context.document.name);
    const compoundKebab = this.toKebabCase(plan.rootName);

    return [
      this.createFile(
        `src/app/${kebab}/page.tsx`,
        `import { ${plan.rootName} } from '@/features/${kebab}/components/${compoundKebab}';\n\nexport default function ${name}Page() {\n  return <${plan.rootName} />;\n}\n`,
        'typescript',
        'screen',
      ),
    ];
  }

  private generateProjectScaffold(_context: GeneratorContext): GeneratedFile[] {
    return [
      this.createFile(
        'src/app/layout.tsx',
        `import type { Metadata } from 'next';\nimport './globals.css';\nimport '../styles/figma-reset.css';\n\nexport const metadata: Metadata = {\n  title: 'Design2Code App',\n  description: 'Pixel-perfect UI from Figma',\n};\n\nexport default function RootLayout({ children }: { children: React.ReactNode }) {\n  return (\n    <html lang="en">\n      <body className="antialiased">{children}</body>\n    </html>\n  );\n}\n`,
        'typescript',
        'project',
      ),
      this.createFile(
        'src/app/globals.css',
        `@tailwind base;\n@tailwind components;\n@tailwind utilities;\n`,
        'css',
        'config',
      ),
      this.createFile(
        'next.config.ts',
        `import type { NextConfig } from 'next';\nconst nextConfig: NextConfig = {};\nexport default nextConfig;\n`,
        'typescript',
        'config',
      ),
    ];
  }
}
