import type { GenerationResult, DesignNode, GeneratedFile } from '@design2code/design-ast';
import { BaseGenerator, type GeneratorContext } from '@design2code/generator-sdk';
import { generateCSSVariables } from '@design2code/design-token-engine';

export class NextjsGenerator extends BaseGenerator {
  readonly name = 'nextjs';
  readonly framework = 'nextjs';

  async generate(context: GeneratorContext): Promise<GenerationResult> {
    const files: GeneratedFile[] = [];
    const nodes = this.filterNodesByScope(context);

    const css = generateCSSVariables(context.document.tokens);
    files.push(this.createFile(css.path, css.content, 'css', 'token'));

    if (context.options.scope === 'component') {
      for (const node of nodes) {
        const name = this.toPascalCase(node.name);
        files.push(
          this.createFile(
            `src/components/${name}.tsx`,
            this.generateServerComponent(node, name),
            'typescript',
            'component',
          ),
        );
      }
    }

    if (context.options.scope === 'screen') {
      for (const screen of context.document.screens) {
        const route = screen.route ?? `/${this.toKebabCase(screen.name)}`;
        const name = this.toPascalCase(screen.name);
        const node = nodes.find((n) => n.id === screen.nodeId) ?? nodes[0];
        if (node) {
          files.push(
            this.createFile(
              `src/app${route}/page.tsx`,
              this.generatePage(node, name, route),
              'typescript',
              'screen',
            ),
          );
        }
      }
    }

    if (context.options.scope === 'feature') {
      files.push(...this.generateFeatureModule(context));
    }

    if (context.options.scope === 'project') {
      files.push(...this.generateProjectScaffold(context));
    }

    return { files, warnings: [], metadata: { framework: 'nextjs', nodeCount: nodes.length } };
  }

  private generateServerComponent(node: DesignNode, name: string): string {
    const body = this.generateJSX(node, 2);
    return `interface ${name}Props {
  className?: string;
}

export function ${name}({ className }: ${name}Props) {
  return (
    <div className={className}>
${body}
    </div>
  );
}
`;
  }

  private generatePage(node: DesignNode, name: string, _route: string): string {
    const body = this.generateJSX(node, 6);
    const title = name.replace(/Page$/, '');

    return `import type { Metadata } from 'next';

export const metadata: Metadata = {
  title: '${title}',
  description: 'Generated by Design2Code AI',
};

export default function ${name}Page() {
  return (
    <main className="min-h-screen p-6">
${body}
    </main>
  );
}
`;
  }

  private generateJSX(node: DesignNode, indent: number): string {
    const pad = '  '.repeat(indent);

    if (node.semanticType === 'button') {
      const label = node.text?.content ?? node.name;
      return `${pad}<button type="button" className="px-6 py-3 bg-indigo-600 text-white rounded-lg font-semibold hover:bg-indigo-700 transition-colors">\n${pad}  ${label}\n${pad}</button>`;
    }

    if (node.type === 'text' && node.text) {
      const size = node.text.fontSize && node.text.fontSize > 24 ? 'text-3xl font-bold' : 'text-base';
      return `${pad}<p className="${size}">${escapeHtml(node.text.content)}</p>`;
    }

    if (node.layout.mode === 'horizontal') {
      const children = node.children.map((c) => this.generateJSX(c, indent + 1)).join('\n');
      return `${pad}<div className="flex flex-row items-center gap-4">\n${children}\n${pad}</div>`;
    }

    if (node.layout.mode === 'vertical') {
      const children = node.children.map((c) => this.generateJSX(c, indent + 1)).join('\n');
      return `${pad}<div className="flex flex-col gap-4">\n${children}\n${pad}</div>`;
    }

    if (node.children.length === 0) {
      const bg = node.style.backgroundColor?.hex ?? 'transparent';
      const radius = node.style.borderRadius?.topLeft ?? 0;
      return `${pad}<div className="rounded-[${radius}px]" style={{ backgroundColor: '${bg}' }} />`;
    }

    const children = node.children.map((c) => this.generateJSX(c, indent + 1)).join('\n');
    return `${pad}<div className="flex flex-col gap-2 p-4">\n${children}\n${pad}</div>`;
  }

  private generateFeatureModule(context: GeneratorContext): GeneratedFile[] {
    const name = this.toPascalCase(context.document.name);
    const kebab = this.toKebabCase(context.document.name);
    return [
      this.createFile(
        `src/features/${kebab}/actions.ts`,
        `'use server';\n\nexport async function get${name}Data() {\n  return { data: [] };\n}\n`,
        'typescript',
        'feature',
      ),
      this.createFile(
        `src/features/${kebab}/components/${name}View.tsx`,
        `export function ${name}View() {\n  return <div>${name} Feature</div>;\n}\n`,
        'typescript',
        'feature',
      ),
      this.createFile(
        `src/app/${kebab}/page.tsx`,
        `import { ${name}View } from '@/features/${kebab}/components/${name}View';\n\nexport default function ${name}Page() {\n  return <${name}View />;\n}\n`,
        'typescript',
        'screen',
      ),
    ];
  }

  private generateProjectScaffold(_context: GeneratorContext): GeneratedFile[] {
    return [
      this.createFile(
        'src/app/layout.tsx',
        `import type { Metadata } from 'next';\nimport './globals.css';\n\nexport const metadata: Metadata = {\n  title: 'Design2Code App',\n  description: 'Generated by Design2Code AI',\n};\n\nexport default function RootLayout({ children }: { children: React.ReactNode }) {\n  return (\n    <html lang="en">\n      <body className="antialiased">{children}</body>\n    </html>\n  );\n}\n`,
        'typescript',
        'project',
      ),
      this.createFile(
        'src/app/page.tsx',
        `export default function HomePage() {\n  return (\n    <main className="flex min-h-screen items-center justify-center">\n      <h1 className="text-4xl font-bold">Design2Code App</h1>\n    </main>\n  );\n}\n`,
        'typescript',
        'screen',
      ),
      this.createFile(
        'src/app/globals.css',
        `@tailwind base;\n@tailwind components;\n@tailwind utilities;\n`,
        'css',
        'config',
      ),
      this.createFile(
        'next.config.ts',
        `import type { NextConfig } from 'next';\n\nconst nextConfig: NextConfig = {};\n\nexport default nextConfig;\n`,
        'typescript',
        'config',
      ),
    ];
  }
}

function escapeHtml(str: string): string {
  return str.replace(/&/g, '&amp;').replace(/</g, '&lt;').replace(/>/g, '&gt;');
}
